<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="../../version.props"></Import>

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Description>A hyper-optimized, zero-allocation console logger for .NET. Writes structured logs and interpolated strings directly to standard output streams without heap allocations, boxing, or garbage collection overhead.</Description>
	</PropertyGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.1" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.20" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.12" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\KetPsi.Extensions.Logging.Abstractions\KetPsi.Extensions.Logging.Abstractions.csproj" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="KetPsi.Extensions.Logging.Tests"/>
		<InternalsVisibleTo Include="KetPsi.Extensions.Logging.Benchmarks"/>
	</ItemGroup>

</Project>
