<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="../../version.props"></Import>

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Description>Core interfaces, compile-time interpolated string handlers, and types for KetPsi's zero-allocation logging framework. Bypasses standard object arrays and boxing to enable absolute zero-allocation structured logging in high-throughput .NET applications.</Description>
	</PropertyGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
	</ItemGroup>
	
	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.20" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
	</ItemGroup>

	<ItemGroup>
		<None Include=".\KetPsi.Extensions.Logging.Generator\bin\$(Configuration)\netstandard2.0\KetPsi.Extensions.Logging.Generator.dll" Pack="true" PackagePath="analyzers\dotnet\cs\KetPsi.Extensions.Logging.Generator.dll" Visible="false" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="KetPsi.Extensions.Logging.Tests"/>
		<InternalsVisibleTo Include="KetPsi.Extensions.Logging.Benchmarks"/>
	</ItemGroup>

</Project>
