name: DeployPackages

on:
  push:
    tags:
      - '*.*.*'
      - '*.*.*-preview'

jobs:
  deploy-prerequisite:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch all branches
        run: git fetch --all

      - name: Verify tag format and branch
        env:
          CI_COMMIT_TAG: ${{ github.ref_name }}
        run: |
          branches=$(git show --no-patch --format=%D $CI_COMMIT_TAG)
          echo "Branches: $branches"
          echo "Tag: $CI_COMMIT_TAG"
          if [[ $branches == *release* && $CI_COMMIT_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+-preview\.[0-9]+$ ]]; then
            echo "Matched Release preview tag pattern"
            exit 0
          elif [[ $branches == *main* && $CI_COMMIT_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Matched Main tag pattern"
            exit 0
          else
            echo "Created tag does not meet requirements."
            exit 1
          fi
      - name: Check for version match in version.props
        env:
          CI_COMMIT_TAG: ${{ github.ref_name }}
        run: |
          if ! grep -q "$CI_COMMIT_TAG" version.props; then
            echo "Version mismatch: $CI_COMMIT_TAG not found in version.props"
            exit 1
          fi
  deploy-abstractions:
    needs: [deploy-prerequisite]
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Pack KetPsi.Extensions.Logging.Abstractions
        id: pack-abstraction
        uses: ./.github/workflows/actions/nuget-pack
        with:
          project_path: src/KetPsi.Extensions.Logging.Abstractions/KetPsi.Extensions.Logging.Abstractions.csproj
      - name: Push KetPsi.Extensions.Logging.Abstractions
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          NUGET_SOURCE: ${{ secrets.NUGET_SOURCE }}
        uses: ./.github/workflows/actions/nuget-push
        with:
          package_path: 'pack/KetPsi.Extensions.Logging.Abstractions.${{ github.ref_name }}.nupkg'

  wait-for-abstractions-package:
    needs: [deploy-abstractions]
    runs-on: self-hosted
    steps:
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.x'
      - name: Wait for KetPsi.Extensions.Logging.Abstractions to be available
        env:
          PACKAGE_NAME: KetPsi.Extensions.Logging.Abstractions
          PACKAGE_VERSION: ${{ github.ref_name }}
        run: |
          for i in {1..20}; do
            dotnet nuget locals all --clear
            if dotnet package search "$PACKAGE_NAME" --exact-match | grep "$PACKAGE_VERSION"; then
              echo "Package is available on NuGet!"
              exit 0
            fi
            echo "Waiting for package to be available on NuGet..."
            sleep 30
          done
          echo "Package did not become available in time." >&2
          exit 1

  deploy-logging-Console:
    needs: [wait-for-abstractions-package]
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Pack KetPsi.Extensions.Logging.Console
        id: pack-console
        uses: ./.github/workflows/actions/nuget-pack
        with:
          project_path: src/KetPsi.Extensions.Logging.Console/KetPsi.Extensions.Logging.Console.csproj
      - name: Push KetPsi.Extensions.Logging.Console
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          NUGET_SOURCE: ${{ secrets.NUGET_SOURCE }}
        uses: ./.github/workflows/actions/nuget-push
        with:
          package_path: 'pack/KetPsi.Extensions.Logging.Console.${{ github.ref_name }}.nupkg'

  deploy-logging-opentelemetry:
    needs: [wait-for-abstractions-package]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Pack KetPsi.Extensions.Logging.OpenTelemetry
        id: pack-opentelemetry
        uses: ./.github/workflows/actions/nuget-pack
        with:
          project_path: src/KetPsi.Extensions.Logging.OpenTelemetry/KetPsi.Extensions.Logging.OpenTelemetry.csproj
      - name: Push KetPsi.Extensions.Logging.OpenTelemetry
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          NUGET_SOURCE: ${{ secrets.NUGET_SOURCE }}
        uses: ./.github/workflows/actions/nuget-push
        with:
          package_path: 'pack/KetPsi.Extensions.Logging.OpenTelemetry.${{ github.ref_name }}.nupkg'